config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  devise_for :students, controllers: {
    omniauth_callbacks: 'students/omniauth_callbacks'
  }
  devise_for :employers
  devise_for :vetters

  # STUDENT UI
  resource :resume, controller: 'students/resume' do
    get 'open'
  end
  resource :contact_info, controller: 'students/contact_info', via: [:patch]

  # EMPLOYERS UI
  get '/resumes' => "employers/resumes#index"
  scope '/resumes' do
    get '/view/:id' => "employers/resumes#show", as: :view_resume
    get '/search' => "employers/resumes#search", as: :search
    get '/inbox' => "employers/resumes#inbox", as: :inbox_resumes
    get '/starred' => "employers/resumes#starred", as: :starred_resumes
    get '/completed' => "employers/resumes#completed", as: :completed_resumes
    get '/ignored' => "employers/resumes#ignored", as: :ignored_resumes
  end
  match "/students/:student_id/progress", to: "employers/progresses#update", via: :put
  get "contact_us" => "employers#contact_us"

  # VETTER UI
  namespace :vetters do
    resources :resumes, only: [:index, :edit, :update] do
      patch 'approve', on: :member
      patch 'reject', on: :member
    end
    resources :companies do
      resources :recruiters
    end
  end

  # Misc
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/employer.rb
##
# New term for this model: RECRUITER

class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable

  belongs_to :company

  def generate_password
    self.password = SecureRandom.hex(4)
  end
end

app/models/vetter.rb
class Vetter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable
end

app/controllers/employers/progresses_controller.rb
class Employers::ProgressesController < EmployersController
  def update
    Progress.set(
      company_id: current_company.id,
      student_id: params[:student_id],
      progress: params[:progress_id])
    render status: :ok, nothing: true
  end
end

app/controllers/employers/resumes_controller.rb
class Employers::ResumesController < EmployersController
  layout 'layouts/employer'
  
  def index
    redirect_to action: :inbox
  end

  def show
    if params[:type] == "new"
      @student_ids = Student.where.not(id: Progress.where(company: current_company).pluck(:student_id))
    else
      set_student_ids_by_progress(params[:type])
    end
    set_resumes
    @resume = @resumes.find_by(student_id: params[:id])
    current_resume_index = @resumes.map(&:student_id).index(params[:id].to_i)
    @next_resume = @resumes[current_resume_index+1]
    @prev_resume = @resumes[current_resume_index-1] if current_resume_index > 0
    respond_to do |format|
      format.html 
      format.js
    end
  end

  def inbox
    @student_ids = Student.where.not(id: Progress.where(company: current_company).pluck(:student_id))
    set_resumes
    render_scoped_index(resumes: @resumes, resumes_type: "New Resumes")
  end

  def starred
    set_student_ids_by_progress(:starred)
    set_resumes
    render_scoped_index(resumes: @resumes, resumes_type: "Starred Resumes")
  end

  def completed
    set_student_ids_by_progress(:completed)
    set_resumes
    render_scoped_index(resumes: @resumes, resumes_type: "Completed Resumes")
  end

  def ignored
    set_student_ids_by_progress(:ignored)
    set_resumes
    render_scoped_index(resumes: @resumes, resumes_type: "Ignored Resumes")
  end

  def search
    begin
      @student = Student.find_by!(student_id: params[:student_id])
      @resume = @student.resume
      redirect_to @resume.file.url
    rescue ActiveRecord::RecordNotFound => e
      if e.model == "Student"
        @title = "Student Not Found"
        @student_id = params[:student_id]
        render :student_not_found, status: 404
      end
    rescue NoMethodError => e
      if e.name == :file
        @title = "Resume Not Uploaded"
        render :resume_not_found, status: 404
      end
    end
  end

  private

  def render_scoped_index(resumes:, resumes_type:)
    @title = resumes_type
    @resumes_json = resumes.collect {|resume| Employers::ResumesSerializer.new(resume)}.to_json
    render :index_scoped
  end

  def set_student_ids_by_progress(progress_id)
    @student_ids = Student.
      where(id: Progress.where(progress: progress_id, company: current_company).
        pluck(:student_id))
  end

  def set_resumes
    @resumes = Resume.for_employers.where(student_id: @student_ids)
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  layout 'layouts/employer'

  before_action :authenticate_employer!, :set_navbar_resume_counts, :set_current_company

  def contact_us
  end

  private

  def set_navbar_resume_counts
    inbox_count = Resume.for_employers.select("distinct student_id").count - Progress.where(company_id: current_company.id).select("distinct student_id").count
    other_counts = Progress.where(company_id: current_company.id).group(:progress).select("distinct student_id").count
    @navbar_resume_counts = other_counts.merge(0 => inbox_count)
  end

  def current_company
    current_employer.company
  end

  def set_current_company
    @current_company = current_company
  end
end

app/controllers/vetters/companies_controller.rb
class Vetters::CompaniesController < VettersController
  def index
    @companies = Company.all.order("name DESC")
    @recruiters_count = Employer.all.group(:company_id).count
  end

  def new
    @company = Company.new
  end

  def create
    Company.create! company_params
    redirect_to vetters_companies_path
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/vetters/employers_controller.rb
class Vetters::EmployersController < VettersController
  def index
    @employers = Employer.order("company_name ASC").all
  end

  def new
    @employer = Employer.new
  end

  def create
    @employer = Employer.new(employer_params)
    @employer.save!
    redirect_to vetters_employers_path
  end

  def edit
    set_employer
  end

  def update
    set_employer
    if @employer.update(employer_params)
      redirect_to vetters_employers_path
    else
      render json: @employer.errors
    end
  end

  private

  def employer_params
    params.require(:employer).permit(:company_name, :name, :email, :password)
  end

  def set_employer
    @employer = Employer.find(params[:id])
  end
end

app/controllers/vetters/recruiters_controller.rb
class Vetters::RecruitersController < VettersController
  before_action :set_company

  def index
    @recruiters = @company.employers
  end

  def new
    @recruiter = @company.employers.new
  end

  def create
    @recruiter = @company.employers.new(recruiter_params)
    @password = @recruiter.generate_password
    @recruiter.save!
    RecruiterMailer.account_created_email(@recruiter, password: @password).deliver_now
    redirect_to action: :index
  end

  private

  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_recruiter
    @recruiter = Employer.find(params[:id])
  end

  def recruiter_params
    params.require(:recruiter).permit(:name, :email)
  end
end

app/controllers/vetters/resumes_controller.rb
class Vetters::ResumesController < VettersController
  def index
    @latest_submissions = Resume.latest_submissions.order("updated_at DESC").includes(:student)
    @pending_resumes  = @latest_submissions.pending
    @approved_resumes = @latest_submissions.approved
    @rejected_resumes = @latest_submissions.rejected
  end

  def show
  end

  def edit
    set_resume
    @rejections_history = Resume.where(student_id: @resume.student_id, status: :rejected)
      .order("created_at DESC")
      .pluck(:rejection_reason)
  end

  def approve
    set_resume
    @resume.approved!
    redirect_to action: :index
    ResumeMailer.approval_email(@resume).deliver_now
  end

  def reject
    set_resume
    @resume.update(reject_resume_params.merge(status: :rejected))
    redirect_to action: :index
    ResumeMailer.rejection_email(@resume).deliver_now
  end

  private

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def reject_resume_params
    params.require(:resume).permit(:rejection_reason)
  end
end

app/controllers/vetters_controller.rb
class VettersController < ApplicationController
  layout 'layouts/vetter'
  before_action :authenticate_vetter!
end

app/views/vetters/employers/edit.html.erb
<div class="container">
  <%= form_for @employer, url: vetters_employer_path(@employer), class: 'form-horizontal' do |form| %>
  <div class="form-group">
    <label for="employer[company_name]" class="col-sm-2 control-label">Company Name</label>
    <div class="col-sm-10">
      <input required type="text" name="employer[company_name]" class="form-control" value="<%= @employer.company_name %>">
    </div>
  </div>
  <div class="form-group">
    <label for="employer[name]" class="col-sm-2 control-label">HR Name</label>
    <div class="col-sm-10">
      <input required type="name" name="employer[name]" class="form-control"  value="<%= @employer.name %>">
    </div>
  </div>
  <div class="form-group">
    <label for="employer[email]" class="col-sm-2 control-label">Login E-mail</label>
    <div class="col-sm-10">
      <input required type="email" name="employer[email]" class="form-control"  value="<%= @employer.email %>">
    </div>
  </div>
  <div class="form-group">
    <label for="employer[password]" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="text" name="employer[password]" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Update</button>
    </div>
  </div>
  <% end %>
</div>

app/views/vetters/employers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h3>Companies</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="col-xs-2">Company</th> 
            <th class="col-xs-3">Name</th>
            <th><%= link_to "New", new_vetters_companies_recruiter_path %></th>
          </tr>
        </thead>
        <tbody>
          <% @employers.each do |employer| %>
          <tr>
            <td><%= employer.company_name %></td>
            <td><%= employer.name %></td>
            <td>
              <%= link_to "Edit", edit_vetters_companies_recruiter_path(employer) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-6">
      <h3>HRs</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="col-xs-2">Company</th> 
            <th class="col-xs-3">Name</th>
            <th><%= link_to "New", new_vetters_employer_path %></th>
          </tr>
        </thead>
        <tbody>
          <% @employers.each do |employer| %>
          <tr>
            <td><%= employer.company_name %></td>
            <td><%= employer.name %></td>
            <td>
              <%= link_to "Edit", edit_vetters_employer_path(employer) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
</div>

app/views/vetters/employers/new.html.erb
<div class="container">
  <%= form_for @employer, url: vetters_employers_path, class: 'form-horizontal' do |form| %>
  <div class="form-group">
    <label for="employer[company_name]" class="col-sm-2 control-label">Company Name</label>
    <div class="col-sm-10">
      <input required type="text" name="employer[company_name]" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <label for="employer[name]" class="col-sm-2 control-label">HR Name</label>
    <div class="col-sm-10">
      <input required type="name" name="employer[name]" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <label for="employer[email]" class="col-sm-2 control-label">Login E-mail</label>
    <div class="col-sm-10">
      <input required type="email" name="employer[email]" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <label for="employer[password]" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input required type="text" name="employer[password]" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Create</button>
    </div>
  </div>
  <% end %>
</div>