config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  devise_for :students, controllers: {
    omniauth_callbacks: 'students/omniauth_callbacks'
  }
  devise_for :employers
  devise_for :vetters

  # STUDENT UI
  resource :resume, controller: 'students/resume' do
    get 'open'
  end
  resource :contact_info, controller: 'students/contact_info', via: [:patch]

  # EMPLOYERS UI
  get '/resumes' => "employers/resumes#index"
  scope '/resumes' do
    get '/view/:id' => "employers/resumes#show", as: :view_resume
    get '/search' => "employers/resumes#search", as: :search
    get '/inbox' => "employers/resumes#inbox", as: :inbox_resumes
    get '/starred' => "employers/resumes#starred", as: :starred_resumes
    get '/completed' => "employers/resumes#completed", as: :completed_resumes
    get '/ignored' => "employers/resumes#ignored", as: :ignored_resumes
  end
  match "/students/:student_id/progress", to: "employers/progresses#update", via: :put
  get "contact_us" => "employers#contact_us"

  # VETTER UI
  namespace :vetters do
    resources :resumes, only: [:index, :edit, :update] do
      patch 'approve', on: :member
      patch 'reject', on: :member
    end
    resources :companies do
      resources :recruiters
    end
  end

  # Misc
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/employer.rb
##
# New term for this model: RECRUITER

class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable

  belongs_to :company

  def generate_password
    self.password = SecureRandom.hex(4)
  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  has_attached_file :file,
    path: ':job_type/:nationality/:student_id-:resume_id.:extension',
    preserve_files: true

  belongs_to :student

  validates :nationality, presence: true
  validates :job_type, presence: true
  validates_attachment :file, presence: true,
    content_type: {content_type: ["application/pdf"]},
    size: { in: 0..1.megabytes }
  validate :resume_has_only_one_page

  enum nationality: {
    malaysian: 1,
    foreigner: 2
  }
  
  enum job_type: {
    full_time: 1,
    internship: 2,
    freelance: 3
  }

  enum status: {
    pending: 0,
    approved: 1,
    rejected: 2
  }

  before_create :generate_reupload_count
  after_create :notify_slackbot_create
  before_save :notify_slackbot_status_changed, if: :status_changed?

  scope :latest_submissions, ->{
    where(id: select("DISTINCT ON(student_id) id")
      .order("student_id, created_at DESC"))
  }

  # I didn't expect there are so little full-timer submissions, I need to 
  # buff them a bit to get noticed.
  #
  # Also need to nerf freelancers coz the 3 submissions too OP
  #
  scope :for_employers, ->{
    latest_submissions.approved.includes(:student).order("job_type ASC")
  }

  private

  def generate_reupload_count
    self.reuploads = student.resumes.count + 1
  end

  def notify_slackbot_create
    SlackbotNotifier.new.notify_resume_upload(self)
  end

  def notify_slackbot_status_changed
    case status
    when "approved"
      SlackbotNotifier.new.notify_resume_approved(self)
    when "rejected"
      SlackbotNotifier.new.notify_resume_rejected(self)
    end
  end

  def resume_has_only_one_page
    return unless file.queued_for_write.any?
    unless PDF::Reader.new(file.queued_for_write[:original].path).page_count == 1
      errors.add("file_one_page", message: "must be 1 page only")
    end
  end

  Paperclip.interpolates :s3_sg_url do |attachment, style|
    "#{attachment.s3_protocol}://s3-ap-southeast-1.amazonaws.com/#{attachment.bucket_name}"
  end

  Paperclip.interpolates :job_type do |attachment, style|
    attachment.instance.job_type
  end

  Paperclip.interpolates :nationality do |attachment, style|
    attachment.instance.nationality
  end

  Paperclip.interpolates :student_id do |attachment, style|
    attachment.instance.student.name.parameterize + 
    '-' + 
    (attachment.instance.student.student_id % 1000).to_s
  end

  Paperclip.interpolates :resume_id do |attachment, style|
    attachment.instance.reuploads
  end
end

app/controllers/employers/progresses_controller.rb
class Employers::ProgressesController < EmployersController
  def update
    Progress.set(
      company_id: current_company.id,
      student_id: params[:student_id],
      progress: params[:progress_id])
    render status: :ok, nothing: true
  end
end

app/controllers/employers/resumes_controller.rb
class Employers::ResumesController < EmployersController
  layout 'layouts/employer'
  
  def index
    redirect_to action: :inbox
  end

  def show
    if params[:type] == "new"
      @student_ids = Student.where.not(id: Progress.where(company: current_company).pluck(:student_id))
    else
      set_student_ids_by_progress(params[:type])
    end
    set_resumes
    @resume = @resumes.find_by(student_id: params[:id])
    current_resume_index = @resumes.map(&:student_id).index(params[:id].to_i)
    @next_resume = @resumes[current_resume_index+1]
    @prev_resume = @resumes[current_resume_index-1] if current_resume_index > 0
    respond_to do |format|
      format.html 
      format.js
    end
  end

  def inbox
    @student_ids = Student.where.not(id: Progress.where(company: current_company).pluck(:student_id))
    set_resumes
    render_scoped_index(resumes: @resumes, resumes_type: "New Resumes")
  end

  def starred
    set_student_ids_by_progress(:starred)
    set_resumes
    render_scoped_index(resumes: @resumes, resumes_type: "Starred Resumes")
  end

  def completed
    set_student_ids_by_progress(:completed)
    set_resumes
    render_scoped_index(resumes: @resumes, resumes_type: "Completed Resumes")
  end

  def ignored
    set_student_ids_by_progress(:ignored)
    set_resumes
    render_scoped_index(resumes: @resumes, resumes_type: "Ignored Resumes")
  end

  def search
    begin
      @student = Student.find_by!(student_id: params[:student_id])
      @resume = @student.resume
      redirect_to @resume.file.url
    rescue ActiveRecord::RecordNotFound => e
      if e.model == "Student"
        @title = "Student Not Found"
        @student_id = params[:student_id]
        render :student_not_found, status: 404
      end
    rescue NoMethodError => e
      if e.name == :file
        @title = "Resume Not Uploaded"
        render :resume_not_found, status: 404
      end
    end
  end

  private

  def render_scoped_index(resumes:, resumes_type:)
    @title = resumes_type
    @resumes_json = resumes.collect {|resume| Employers::ResumesSerializer.new(resume)}.to_json
    render :index_scoped
  end

  def set_student_ids_by_progress(progress_id)
    @student_ids = Student.
      where(id: Progress.where(progress: progress_id, company: current_company).
        pluck(:student_id))
  end

  def set_resumes
    @resumes = Resume.for_employers.where(student_id: @student_ids)
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  layout 'layouts/employer'

  before_action :authenticate_employer!, :set_navbar_resume_counts, :set_current_company

  def contact_us
  end

  private

  def set_navbar_resume_counts
    inbox_count = Resume.for_employers.select("distinct student_id").count - Progress.where(company_id: current_company.id).select("distinct student_id").count
    other_counts = Progress.where(company_id: current_company.id).group(:progress).select("distinct student_id").count
    @navbar_resume_counts = other_counts.merge(0 => inbox_count)
  end

  def current_company
    current_employer.company
  end

  def set_current_company
    @current_company = current_company
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  layout 'layouts/student'
  
  before_action :authenticate_student!
  
  def show
    set_resume
  end

  def new
    new_resume
  end

  def create
    create_resume
    if @resume.persisted?
      redirect_to resume_path
    else
      redirect_to new_resume_path, flash: {errors: @resume.errors}
    end
  end

  def open
    set_resume
    redirect_to @resume.file.url
  end

  private

  def set_resume
    @resume = current_student.resume
  end

  def new_resume
    @resume = current_student.resumes.new
  end

  def create_resume
    @resume = current_student.resumes.create(resume_params)
  end

  def resume_params
    params.require(:resume).permit(:file, :nationality, :job_type)
  end
end

app/controllers/students/resume_controller.rb
class Students::ResumeController < StudentsController

  def show
    set_student
    set_resume
    @starred_companies = Company.where(id: Progress.where(student_id: @student.id, progress: "starred").pluck(:company_id)).pluck(:name)
  end

  def new
    new_resume
  end

  def create
    create_resume
    if @resume.persisted?
      redirect_to resume_path
    else
      redirect_to new_resume_path, flash: {errors: @resume.errors}
    end
  end

  def open
    set_resume
    redirect_to @resume.file.url
  end

  private

  def set_student
    @student = current_student
  end

  def set_resume
    @resume = current_student.resume
  end

  def new_resume
    @resume = current_student.resumes.new
  end

  def create_resume
    @resume = current_student.resumes.create(resume_params)
  end

  def resume_params
    params.require(:resume).permit(:file, :nationality, :job_type, :isCS)
  end
end

app/controllers/vetters/employers_controller.rb
class Vetters::EmployersController < VettersController
  def index
    @employers = Employer.order("company_name ASC").all
  end

  def new
    @employer = Employer.new
  end

  def create
    @employer = Employer.new(employer_params)
    @employer.save!
    redirect_to vetters_employers_path
  end

  def edit
    set_employer
  end

  def update
    set_employer
    if @employer.update(employer_params)
      redirect_to vetters_employers_path
    else
      render json: @employer.errors
    end
  end

  private

  def employer_params
    params.require(:employer).permit(:company_name, :name, :email, :password)
  end

  def set_employer
    @employer = Employer.find(params[:id])
  end
end

app/controllers/vetters/resumes_controller.rb
class Vetters::ResumesController < VettersController
  def index
    @latest_submissions = Resume.latest_submissions.order("updated_at DESC").includes(:student)
    @pending_resumes  = @latest_submissions.pending
    @approved_resumes = @latest_submissions.approved
    @rejected_resumes = @latest_submissions.rejected
  end

  def show
  end

  def edit
    set_resume
    @rejections_history = Resume.where(student_id: @resume.student_id, status: :rejected)
      .order("created_at DESC")
      .pluck(:rejection_reason)
  end

  def approve
    set_resume
    @resume.approved!
    redirect_to action: :index
    ResumeMailer.approval_email(@resume).deliver_now
  end

  def reject
    set_resume
    @resume.update(reject_resume_params.merge(status: :rejected))
    redirect_to action: :index
    ResumeMailer.rejection_email(@resume).deliver_now
  end

  private

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def reject_resume_params
    params.require(:resume).permit(:rejection_reason)
  end
end

app/views/employers/resumes/_index_mobile.html.erb
<div class="panel panel-default panel-resume" ng-repeat="resume in resumes | filter:search_term" ng-cloak>
  <div class="panel-body">
    <h4>{{ resume.student_name }}</h4>
    <div class="pull-left">
      <a href="mailto:{{ resume.student_email }}" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-envelope"></span>
      </a>
      <a href="tel:{{ resume.student_phone }}" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-earphone"></span>
      </a>
    </div>
    <div class="pull-right">
      <a href="{{ resume.file_url }}" class="btn btn-primary btn-sm" target="_blank">
        <span class="glyphicon glyphicon-file"></span>
      </a>
    </div>
</div>

app/views/employers/resumes/_index_tables.html.erb
<table class="table table-hover hidden-xs">
  <thead>
    <tr>
      <th class="col-xs-1">Title</th>
      <th class="col-xs-1">Job Type</th>
      <th class="col-xs-2">Name (University)</th>
      <th class="col-xs-1">Student ID</th>
      <th class="col-xs-1">Nationality</th>
      <th class="col-xs-1">Phone</th>
      <th class="col-xs-1">Job type</th>
      <th class="class col-xs-2">E-mail Address</th>
      <th class="col-xs-2">Move To</th>
    </tr>
  </thead>
  <tbody>
  <style>
    .table_row {
      display: none;
    }
    .show_table {
      display: table-row;
    }
  </style>
    <tr ng-repeat="resume in resumes | filter:search_term" ng-cloak class = "table_row {{ resume.isCS ? 'ITCS' : 'nonITCS' }}">
      <td><%= @title %></td>
      <td>{{ resume.job_type }}</td>
      <td><a href = "/resumes/view/{{ resume.student_id }}?type=<%=@title[/(\S+)/, 1].downcase %>">{{ resume.student_name }} ({{ resume.university }})</a></td>
      <td>{{ resume.mmu_id }}</td>
      <td>{{ resume.nationality }}</td>
      <td><a href="tel:{{ resume.student_phone }}">{{ resume.student_phone }}</a></td>
      <td> {{ resume.isCS ? "IT/CS-related" : "Others" }}
        
      </td>
      <td><a href="mailto:{{ resume.student_email }}">{{ resume.student_email }}</a></td>
      <td>
        <% unless current_page?(inbox_resumes_path) %>
          <a href="#" class="btn btn-xs btn-default"
            ng-click="update_student_progress($index, 'inbox')">Inbox</a>
        <% end %>
        <% unless current_page?(starred_resumes_path) %>
          <a href="#" class="btn btn-xs btn-primary" 
            ng-click="update_student_progress($index, 'starred')">Star</a>
        <% end %>
        <% unless current_page?(completed_resumes_path) %>
          <a href="#" class="btn btn-xs btn-success"
            ng-click="update_student_progress($index, 'completed')">Complete</a>
        <% end %>
        <% unless current_page?(ignored_resumes_path) %>
          <a href="#" class="btn btn-xs btn-danger"
            ng-click="update_student_progress($index, 'ignored')">Ignore</a>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
  <script>
  $(document).ready(function(){
    var boxIT = document.querySelector("input#IT");
    var nonBoxIT = document.querySelector("input#non-IT");
    var studentIT = document.querySelectorAll("tr.ITCS");
    var studentNonIT = document.querySelectorAll("tr.nonITCS");
    for (var i = 0; i < studentIT.length; i++){
          studentIT[i].classList.add("show_table");
        }
    boxIT.addEventListener("change", function(){
      if(this.checked){
        for (var i = 0; i < studentIT.length; i++){
          studentIT[i].classList.add("show_table");
        }
      }else{
        for (var i = 0; i < studentIT.length; i++){
          studentIT[i].classList.remove("show_table");
        }
      }

    });
    nonBoxIT.addEventListener("change", function(){
      if (this.checked){
        for (var i = 0; i < studentNonIT.length; i++){
          studentNonIT[i].classList.add("show_table");
        }
      }else{
        for (var i = 0; i < studentNonIT.length; i++){
          studentNonIT[i].classList.remove("show_table");
        }
      }
    });
  });

  </script>

app/views/employers/resumes/index.html.erb
<div class="container">
  <h1>Bookmarks</h1>
  <p>Bookmark this page on your phone, enter a student's ID to open their resume fast.</p>
</div>

app/views/employers/resumes/index_scoped.html.erb
<div class="container" ng-controller="resumes_index_controller" ng-init="init()">
  <!-- Desktop UI -->
  <div class="row hidden-xs">
    <div class="col-xs-8" >
      <input class="form-control" ng-model="search_term" placeholder="Search resume..." />
    </div>
    <div class="col-xs-4">
      <label>IT/CS</label>
      <input type="checkbox" id = "IT" checked>
      <label>Non IT/CS</label>
      <input type="checkbox" id = "non-IT">
    </div>
  </div>
  <%= render 'index_tables' %>
  <!-- Mobile friendly UI -->
  <div class="visible-xs">
    <%= render 'index_mobile' %>
  </div>
  <!-- Data -->
  <script type="application/json" id="resumes_json"><%= @resumes_json.html_safe %></script>

</div>

app/views/employers/resumes/resume_not_found.html.erb
<div class="container">
  <h1>No Resume Uploaded</h1>
  <p><%= @student.name %> has yet to upload a resume.</p>
</div>

app/views/employers/resumes/show.html.erb
<div class = "content-container" id = "resume-container">
	<div class = "left-fixed">
		<% if !@prev_resume.nil? %>
		<%= link_to "Prev", view_resume_path(@prev_resume.student_id, type: params[:type]), class: "nav-left" %>
		<% end %>
	</div>

	<div class = "view-area">
  	<div class="viewer-box">
    	<iframe class = "iframe-box" src="<%= @resume.file.url %>"></iframe>
  	</div>
  	<div class = "link-box">
			<%= link_to "Open in a new window", @resume.file.url, target: "_blank" %>
  	</div>
	</div>

	<div class ="right-fixed">
		<% if !@next_resume.nil? %>
		<%= link_to "Next", view_resume_path(@next_resume.student_id, type: params[:type]), class: "nav-right" %>
		<% end %>
	</div>
</div>

app/views/employers/resumes/show.js.erb
$("#resume-container").html("<%= escape_javascript(render("employers/resumes/show")) %>");

app/views/employers/resumes/student_not_found.html.erb
<div class="container">
  <h1>Oops!</h1>
  <p>We can't find the student with ID <b><%= @student_id %></b>. </p>
  <p>They haven't logged into our site before.</p>
</div>