config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  devise_for :students, controllers: {
    omniauth_callbacks: 'students/omniauth_callbacks'
  }
  devise_for :employers
  devise_for :vetters

  # STUDENT UI
  resource :resume, controller: 'students/resume' do
    get 'open'
  end
  resource :contact_info, controller: 'students/contact_info', via: [:patch]

  # EMPLOYERS UI
  get '/resumes' => "employers/resumes#index"
  scope '/resumes' do
    get '/view/:id' => "employers/resumes#show", as: :view_resume
    get '/search' => "employers/resumes#search", as: :search
    get '/inbox' => "employers/resumes#inbox", as: :inbox_resumes
    get '/starred' => "employers/resumes#starred", as: :starred_resumes
    get '/completed' => "employers/resumes#completed", as: :completed_resumes
    get '/ignored' => "employers/resumes#ignored", as: :ignored_resumes
  end
  match "/students/:student_id/progress", to: "employers/progresses#update", via: :put
  get "contact_us" => "employers#contact_us"

  # VETTER UI
  namespace :vetters do
    resources :resumes, only: [:index, :edit, :update] do
      patch 'approve', on: :member
      patch 'reject', on: :member
    end
    resources :companies do
      resources :recruiters
    end
  end

  # Misc
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/vetter.rb
class Vetter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable
end

app/controllers/vetters/companies_controller.rb
class Vetters::CompaniesController < VettersController
  def index
    @companies = Company.all.order("name DESC")
    @recruiters_count = Employer.all.group(:company_id).count
  end

  def new
    @company = Company.new
  end

  def create
    Company.create! company_params
    redirect_to vetters_companies_path
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/vetters/employers_controller.rb
class Vetters::EmployersController < VettersController
  def index
    @employers = Employer.order("company_name ASC").all
  end

  def new
    @employer = Employer.new
  end

  def create
    @employer = Employer.new(employer_params)
    @employer.save!
    redirect_to vetters_employers_path
  end

  def edit
    set_employer
  end

  def update
    set_employer
    if @employer.update(employer_params)
      redirect_to vetters_employers_path
    else
      render json: @employer.errors
    end
  end

  private

  def employer_params
    params.require(:employer).permit(:company_name, :name, :email, :password)
  end

  def set_employer
    @employer = Employer.find(params[:id])
  end
end

app/controllers/vetters/recruiters_controller.rb
class Vetters::RecruitersController < VettersController
  before_action :set_company

  def index
    @recruiters = @company.employers
  end

  def new
    @recruiter = @company.employers.new
  end

  def create
    @recruiter = @company.employers.new(recruiter_params)
    @password = @recruiter.generate_password
    @recruiter.save!
    RecruiterMailer.account_created_email(@recruiter, password: @password).deliver_now
    redirect_to action: :index
  end

  private

  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_recruiter
    @recruiter = Employer.find(params[:id])
  end

  def recruiter_params
    params.require(:recruiter).permit(:name, :email)
  end
end

app/controllers/vetters/resumes_controller.rb
class Vetters::ResumesController < VettersController
  def index
    @latest_submissions = Resume.latest_submissions.order("updated_at DESC").includes(:student)
    @pending_resumes  = @latest_submissions.pending
    @approved_resumes = @latest_submissions.approved
    @rejected_resumes = @latest_submissions.rejected
  end

  def show
  end

  def edit
    set_resume
    @rejections_history = Resume.where(student_id: @resume.student_id, status: :rejected)
      .order("created_at DESC")
      .pluck(:rejection_reason)
  end

  def approve
    set_resume
    @resume.approved!
    redirect_to action: :index
    ResumeMailer.approval_email(@resume).deliver_now
  end

  def reject
    set_resume
    @resume.update(reject_resume_params.merge(status: :rejected))
    redirect_to action: :index
    ResumeMailer.rejection_email(@resume).deliver_now
  end

  private

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def reject_resume_params
    params.require(:resume).permit(:rejection_reason)
  end
end

app/controllers/vetters_controller.rb
class VettersController < ApplicationController
  layout 'layouts/vetter'
  before_action :authenticate_vetter!
end

app/views/vetters/recruiters/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2><%= @company.name %></h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="col-xs-3">Name</th>
            <th class="col-xs-3">E-mail Address</th>
            <th class="col-xs-3">Last Login</th>
            <th><%= link_to "New", new_vetters_company_recruiter_path(@company) %></th>
          </tr>
        </thead>
        <tbody>
          <% @recruiters.each do |recruiter| %>
          <tr>
            <td><%= recruiter.name %></td>
            <td><%= recruiter.email %></td>
            <td><%= recruiter.last_sign_in_at ? time_ago_in_words(recruiter.last_sign_in_at) + " ago" : "Never" %></td>
            <td>
              <%= link_to "Edit", edit_vetters_company_recruiter_path(@company, recruiter) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
</div>

app/views/vetters/recruiters/new.html.erb
<div class="container">
  <h2>Create Recruiter For <%= @company.name %></h2>
  <%= form_for(@recruiter, url: vetters_company_recruiters_path, html: {class: 'form-horizontal'}) do |form| %>
  <div class="form-group">
    <label for="recruiter[name]" class="col-sm-2 control-label">HR Name</label>
    <div class="col-sm-10">
      <input required type="name" name="recruiter[name]" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <label for="recruiter[email]" class="col-sm-2 control-label">Login E-mail</label>
    <div class="col-sm-10">
      <input required type="email" name="recruiter[email]" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Create &amp; Send E-mail</button>
      <small>A 8 characters long password will be randomly generated and the credentials will be sent to the recruiter.</small>
    </div>
  </div>
  <% end %>
</div>