config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  devise_for :students, controllers: {
    omniauth_callbacks: 'students/omniauth_callbacks'
  }
  devise_for :employers
  devise_for :vetters

  # STUDENT UI
  resource :resume, controller: 'students/resume' do
    get 'open'
  end
  resource :contact_info, controller: 'students/contact_info', via: [:patch]

  # EMPLOYERS UI
  get '/resumes' => "employers/resumes#index"
  scope '/resumes' do
    get '/view/:id' => "employers/resumes#show", as: :view_resume
    get '/search' => "employers/resumes#search", as: :search
    get '/inbox' => "employers/resumes#inbox", as: :inbox_resumes
    get '/starred' => "employers/resumes#starred", as: :starred_resumes
    get '/completed' => "employers/resumes#completed", as: :completed_resumes
    get '/ignored' => "employers/resumes#ignored", as: :ignored_resumes
  end
  match "/students/:student_id/progress", to: "employers/progresses#update", via: :put
  get "contact_us" => "employers#contact_us"

  # VETTER UI
  namespace :vetters do
    resources :resumes, only: [:index, :edit, :update] do
      patch 'approve', on: :member
      patch 'reject', on: :member
    end
    resources :companies do
      resources :recruiters
    end
  end

  # Misc
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/views/layouts/_employer_navbar.html.erb
<nav class="navbar navbar-default navbar-employer">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "IJE for Employer", resumes_path, class: "navbar-brand" %>
    </div>

    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(inbox_resumes_path) %>">
          <%= link_to inbox_resumes_path do %>
            Inbox <span class="label label-default"><%= @navbar_resume_counts[0] %></span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(starred_resumes_path) %>">
          <%= link_to starred_resumes_path do %>
            Starred <span class="label label-default"><%= @navbar_resume_counts[1] %></span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(completed_resumes_path) %>">
          <%= link_to completed_resumes_path do %>
            Completed <span class="label label-default"><%= @navbar_resume_counts[2] || 0 %></span>
          <% end -%>
        </li>
        <li class="<%= 'active' if current_page?(ignored_resumes_path) %>">
          <%= link_to ignored_resumes_path do %>
            Ignored <span class="label label-default"><%= @navbar_resume_counts[3] || 0 %></span>
          <% end -%>
        </li>
        <li class="<%= 'active' if current_page?(contact_us_path) %>">
          <%= link_to "Contact Us", contact_us_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Logout", destroy_employer_session_path, method: :delete %>
        </li>
      </ul>
      <form class="navbar-form navbar-right" method="GET" action="/resumes/search">
        <div class="form-group">
          <input type="tel" name="student_id" class="form-control" placeholder="Student ID" title="MMU Student IDs are 10 digits long" required>
          <button type="submit" class="btn btn-default">Open Resume</button>
        </div>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">IJE Resume</a>
    </div>
</nav>

app/views/layouts/_other_scripts.html.erb
<!-- <script data-align="right" data-overlay="false" id="keyreply-script" src="//keyreply.com/chat/widget.js" data-color="#03A9F4" data-apps="JTdCJTIyZmFjZWJvb2slMjI6JTIyaXRjd21tdSUyMiwlMjJlbWFpbCUyMjolMjJpdHNvYy5tbXVAZ21haWwuY29tJTIyJTdE"></script> -->
<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GA_TRACKING_ID'] %>', 'auto');
  ga('send', 'pageview');

</script>
<% end %>

app/views/layouts/_student_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">IJE Resume</a>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "Upload Resume", resume_path %>
        </li>
        <li>
          <a href="https://www.eventbrite.com/e/tech-career-days-mmu-tickets-39367831243?aff=tcdresume">Register For Ticket</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Logout", destroy_student_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_vetter_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">IJE Resume</a>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(vetters_resumes_path) %>">
          <%= link_to "Resumes (#{ Resume.latest_submissions.pending.count })", vetters_resumes_path %>
        </li>
        <li class="<%= 'active' if current_page?(vetters_companies_path) %>">
          <%= link_to "Companies & Recruiters", vetters_companies_path %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Logout", destroy_vetter_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "IJE Resume" %></title>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/other_scripts' %>
  </body>
</html>

app/views/layouts/employer.html.erb
<!DOCTYPE html>
<html ng-app="employers">
  <head>
    <title><%= @title || "IJE Employers Dashboard" %></title>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'employers' %>
  </head>

  <body>
    <%= render 'layouts/employer_navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <toaster-container></toaster-container>
    <%= render 'layouts/other_scripts' %>
    <%= render 'layouts/intercom/employers' %>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "IJE Resume " %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Submit Your Resume Now - IT Job Expo MMU Cyberjaya</title>
    <meta property="og:title" content="Submit Your Resume For IT Job Expo MMU Cyberjaya" />
    <meta property="og:description" content="Upload your resume.pdf and get contacted by the exhibiting employers prior to the event. IT Job Expo will happen in 
    Learning Point, MMU Cyberjaya on 14-15 January 2019. Click to learn more.">
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://resumetcd.herokuapp.com/" />
    <meta property="og:image" content="https://resumetcd.herokuapp.com/opengraph-v2.png" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/other_scripts' %>
  </body>
</html>

app/views/layouts/student.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "IJE Resume" %></title>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/student_navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/other_scripts' %>
    <%= render 'layouts/intercom/students' %>
  </body>
</html>

app/views/layouts/vetter.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IJE Employers Dashboard</title>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/vetter_navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/other_scripts' %>
  </body>
</html>